### ISSUE TITLE
Виджет чатры закрывает оранжевый кружочек снизу справа

### ISSUE THREAD

**Issue by f213** [tough-dev-school/lms-frontend#101]
![2022-01-26 19 39 41](https://user-images.githubusercontent.com/1592663/151206788-d177cd45-5cd4-4a39-ad31-fa6640b13290.jpg)

Надо разобраться, что это за кружочек и найти ему новое место

**Comment by peacefulseeker** [comment]
появляется при разрешении экрана < 800px;
открывает советы по обратной связи 
![image](https://user-images.githubusercontent.com/25010454/151574579-6ff3bbf4-a4ef-4301-a537-d2104a2929ae.png)
